-- Materialized by Python's tested as-of feature builder. One snapshot per run.
CREATE TABLE IF NOT EXISTS account_features (
    customer_id VARCHAR NOT NULL,
    scoring_date DATE NOT NULL,
    industry VARCHAR,
    region VARCHAR,
    company_size VARCHAR,
    account_start_date DATE,
    acquisition_cohort VARCHAR,
    product_family VARCHAR,
    account_age_months FLOAT,
    months_until_renewal FLOAT,
    previous_renewals FLOAT,
    hardware_age FLOAT,
    months_until_end_of_service FLOAT,
    number_of_arrays INTEGER,
    total_capacity_tb FLOAT,
    storage_utilization FLOAT,
    data_growth FLOAT,
    utilization_3m_change FLOAT,
    utilization_6m_slope FLOAT,
    support_tickets_30d FLOAT,
    support_tickets_90d FLOAT,
    critical_incidents_90d FLOAT,
    ARR FLOAT,
    ARR_growth_12m FLOAT,
    expansion_last_12m FLOAT,
    number_of_previous_expansions FLOAT,
    PRIMARY KEY (customer_id, scoring_date)
);
