[theme]
primaryColor = "#0F766E"
backgroundColor = "#F7F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#142536"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
